name: mixkage_sber_code
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.7
  intl: ^0.19.0
  logger: ^2.4.0
  motion: ^2.0.0
  sentry_flutter: ^8.9.0
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  spider: ^4.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n/res
  output_dir: lib/l10n
